/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as RadarLovableRouteImport } from './routes/radar-lovable'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as ClaudeRouteImport } from './routes/claude'
import { Route as AudiosRouteImport } from './routes/audios'
import { Route as IndexRouteImport } from './routes/index'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarLovableRoute = RadarLovableRouteImport.update({
  id: '/radar-lovable',
  path: '/radar-lovable',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeRoute = ClaudeRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiosRoute = AudiosRouteImport.update({
  id: '/audios',
  path: '/audios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audios': typeof AudiosRoute
  '/claude': typeof ClaudeRoute
  '/pulse': typeof PulseRoute
  '/radar-lovable': typeof RadarLovableRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audios': typeof AudiosRoute
  '/claude': typeof ClaudeRoute
  '/pulse': typeof PulseRoute
  '/radar-lovable': typeof RadarLovableRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audios': typeof AudiosRoute
  '/claude': typeof ClaudeRoute
  '/pulse': typeof PulseRoute
  '/radar-lovable': typeof RadarLovableRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audios'
    | '/claude'
    | '/pulse'
    | '/radar-lovable'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audios' | '/claude' | '/pulse' | '/radar-lovable' | '/voice'
  id:
    | '__root__'
    | '/'
    | '/audios'
    | '/claude'
    | '/pulse'
    | '/radar-lovable'
    | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudiosRoute: typeof AudiosRoute
  ClaudeRoute: typeof ClaudeRoute
  PulseRoute: typeof PulseRoute
  RadarLovableRoute: typeof RadarLovableRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar-lovable': {
      id: '/radar-lovable'
      path: '/radar-lovable'
      fullPath: '/radar-lovable'
      preLoaderRoute: typeof RadarLovableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude': {
      id: '/claude'
      path: '/claude'
      fullPath: '/claude'
      preLoaderRoute: typeof ClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audios': {
      id: '/audios'
      path: '/audios'
      fullPath: '/audios'
      preLoaderRoute: typeof AudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudiosRoute: AudiosRoute,
  ClaudeRoute: ClaudeRoute,
  PulseRoute: PulseRoute,
  RadarLovableRoute: RadarLovableRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
