/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TextotesteRouteImport } from './routes/textoteste'
import { Route as RagmodelosRouteImport } from './routes/ragmodelos'
import { Route as RadarLovableRouteImport } from './routes/radar-lovable'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as ImagensRouteImport } from './routes/imagens'
import { Route as ElitelovableRouteImport } from './routes/elitelovable'
import { Route as ClaudeRouteImport } from './routes/claude'
import { Route as ChatmodelosRouteImport } from './routes/chatmodelos'
import { Route as AudiosRouteImport } from './routes/audios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateImageGoogleRouteImport } from './routes/api/generate-image-google'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiPublicElitePromptRouteImport } from './routes/api/public/elite-prompt'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TextotesteRoute = TextotesteRouteImport.update({
  id: '/textoteste',
  path: '/textoteste',
  getParentRoute: () => rootRouteImport,
} as any)
const RagmodelosRoute = RagmodelosRouteImport.update({
  id: '/ragmodelos',
  path: '/ragmodelos',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarLovableRoute = RadarLovableRouteImport.update({
  id: '/radar-lovable',
  path: '/radar-lovable',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagensRoute = ImagensRouteImport.update({
  id: '/imagens',
  path: '/imagens',
  getParentRoute: () => rootRouteImport,
} as any)
const ElitelovableRoute = ElitelovableRouteImport.update({
  id: '/elitelovable',
  path: '/elitelovable',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeRoute = ClaudeRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatmodelosRoute = ChatmodelosRouteImport.update({
  id: '/chatmodelos',
  path: '/chatmodelos',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiosRoute = AudiosRouteImport.update({
  id: '/audios',
  path: '/audios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageGoogleRoute = ApiGenerateImageGoogleRouteImport.update({
  id: '/api/generate-image-google',
  path: '/api/generate-image-google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicElitePromptRoute = ApiPublicElitePromptRouteImport.update({
  id: '/api/public/elite-prompt',
  path: '/api/public/elite-prompt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audios': typeof AudiosRoute
  '/chatmodelos': typeof ChatmodelosRoute
  '/claude': typeof ClaudeRoute
  '/elitelovable': typeof ElitelovableRoute
  '/imagens': typeof ImagensRoute
  '/modelos': typeof ModelosRoute
  '/pulse': typeof PulseRoute
  '/radar-lovable': typeof RadarLovableRoute
  '/ragmodelos': typeof RagmodelosRoute
  '/textoteste': typeof TextotesteRoute
  '/voice': typeof VoiceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-image-google': typeof ApiGenerateImageGoogleRoute
  '/api/public/elite-prompt': typeof ApiPublicElitePromptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audios': typeof AudiosRoute
  '/chatmodelos': typeof ChatmodelosRoute
  '/claude': typeof ClaudeRoute
  '/elitelovable': typeof ElitelovableRoute
  '/imagens': typeof ImagensRoute
  '/modelos': typeof ModelosRoute
  '/pulse': typeof PulseRoute
  '/radar-lovable': typeof RadarLovableRoute
  '/ragmodelos': typeof RagmodelosRoute
  '/textoteste': typeof TextotesteRoute
  '/voice': typeof VoiceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-image-google': typeof ApiGenerateImageGoogleRoute
  '/api/public/elite-prompt': typeof ApiPublicElitePromptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audios': typeof AudiosRoute
  '/chatmodelos': typeof ChatmodelosRoute
  '/claude': typeof ClaudeRoute
  '/elitelovable': typeof ElitelovableRoute
  '/imagens': typeof ImagensRoute
  '/modelos': typeof ModelosRoute
  '/pulse': typeof PulseRoute
  '/radar-lovable': typeof RadarLovableRoute
  '/ragmodelos': typeof RagmodelosRoute
  '/textoteste': typeof TextotesteRoute
  '/voice': typeof VoiceRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-image-google': typeof ApiGenerateImageGoogleRoute
  '/api/public/elite-prompt': typeof ApiPublicElitePromptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audios'
    | '/chatmodelos'
    | '/claude'
    | '/elitelovable'
    | '/imagens'
    | '/modelos'
    | '/pulse'
    | '/radar-lovable'
    | '/ragmodelos'
    | '/textoteste'
    | '/voice'
    | '/api/generate-image'
    | '/api/generate-image-google'
    | '/api/public/elite-prompt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audios'
    | '/chatmodelos'
    | '/claude'
    | '/elitelovable'
    | '/imagens'
    | '/modelos'
    | '/pulse'
    | '/radar-lovable'
    | '/ragmodelos'
    | '/textoteste'
    | '/voice'
    | '/api/generate-image'
    | '/api/generate-image-google'
    | '/api/public/elite-prompt'
  id:
    | '__root__'
    | '/'
    | '/audios'
    | '/chatmodelos'
    | '/claude'
    | '/elitelovable'
    | '/imagens'
    | '/modelos'
    | '/pulse'
    | '/radar-lovable'
    | '/ragmodelos'
    | '/textoteste'
    | '/voice'
    | '/api/generate-image'
    | '/api/generate-image-google'
    | '/api/public/elite-prompt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudiosRoute: typeof AudiosRoute
  ChatmodelosRoute: typeof ChatmodelosRoute
  ClaudeRoute: typeof ClaudeRoute
  ElitelovableRoute: typeof ElitelovableRoute
  ImagensRoute: typeof ImagensRoute
  ModelosRoute: typeof ModelosRoute
  PulseRoute: typeof PulseRoute
  RadarLovableRoute: typeof RadarLovableRoute
  RagmodelosRoute: typeof RagmodelosRoute
  TextotesteRoute: typeof TextotesteRoute
  VoiceRoute: typeof VoiceRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGenerateImageGoogleRoute: typeof ApiGenerateImageGoogleRoute
  ApiPublicElitePromptRoute: typeof ApiPublicElitePromptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textoteste': {
      id: '/textoteste'
      path: '/textoteste'
      fullPath: '/textoteste'
      preLoaderRoute: typeof TextotesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ragmodelos': {
      id: '/ragmodelos'
      path: '/ragmodelos'
      fullPath: '/ragmodelos'
      preLoaderRoute: typeof RagmodelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar-lovable': {
      id: '/radar-lovable'
      path: '/radar-lovable'
      fullPath: '/radar-lovable'
      preLoaderRoute: typeof RadarLovableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagens': {
      id: '/imagens'
      path: '/imagens'
      fullPath: '/imagens'
      preLoaderRoute: typeof ImagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elitelovable': {
      id: '/elitelovable'
      path: '/elitelovable'
      fullPath: '/elitelovable'
      preLoaderRoute: typeof ElitelovableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude': {
      id: '/claude'
      path: '/claude'
      fullPath: '/claude'
      preLoaderRoute: typeof ClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatmodelos': {
      id: '/chatmodelos'
      path: '/chatmodelos'
      fullPath: '/chatmodelos'
      preLoaderRoute: typeof ChatmodelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audios': {
      id: '/audios'
      path: '/audios'
      fullPath: '/audios'
      preLoaderRoute: typeof AudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image-google': {
      id: '/api/generate-image-google'
      path: '/api/generate-image-google'
      fullPath: '/api/generate-image-google'
      preLoaderRoute: typeof ApiGenerateImageGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elite-prompt': {
      id: '/api/public/elite-prompt'
      path: '/api/public/elite-prompt'
      fullPath: '/api/public/elite-prompt'
      preLoaderRoute: typeof ApiPublicElitePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudiosRoute: AudiosRoute,
  ChatmodelosRoute: ChatmodelosRoute,
  ClaudeRoute: ClaudeRoute,
  ElitelovableRoute: ElitelovableRoute,
  ImagensRoute: ImagensRoute,
  ModelosRoute: ModelosRoute,
  PulseRoute: PulseRoute,
  RadarLovableRoute: RadarLovableRoute,
  RagmodelosRoute: RagmodelosRoute,
  TextotesteRoute: TextotesteRoute,
  VoiceRoute: VoiceRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGenerateImageGoogleRoute: ApiGenerateImageGoogleRoute,
  ApiPublicElitePromptRoute: ApiPublicElitePromptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
